package database

const (
	RESOURCE_TABLE = 0 + iota
	SHORTERM_TABLE
	LONGTERM_TABLE
)

const (
	UNIXTIME_TO_DAY                       = 86400
	DATE_FORMAT                           = "06010200"
	METRIC_VAR_NODE                       = "node"
	METRIC_VAR_POD                        = "pod"
	METRIC_VAR_CONTAINER                  = "container"
	METRIC_VAR_NAMESPACE                  = "namespace"
	METRIC_VAR_METRICID                   = "metricid"
	METRIC_VAR_DEVICE                     = "device"
	METRIC_VAR_INTERFACE                  = "interface"
	METRIC_VAR_TIMESTAMPMS                = "timestampms"
	METRIC_VAR_CPUUSAGESEONDSTOTAL        = "cpuusagesecondstotal"
	METRIC_VAR_CPUSYSTEMSECONDSTOTAL      = "cpusystemsecondstotal"
	METRIC_VAR_CPUUSERSECONDSTOTAL        = "cpuusersecondstotal"
	METRIC_VAR_MEMORYUSAGEBYTES           = "memoryusagebytes"
	METRIC_VAR_MEMORYWORKINGSETBYTES      = "memoryworkingsetbytes"
	METRIC_VAR_MEMORYCACHE                = "memorycache"
	METRIC_VAR_MEMORYSWAP                 = "memoryswap"
	METRIC_VAR_MEMORYRSS                  = "memoryrss"
	METRIC_VAR_FSINODESFREE               = "fsinodesfree"
	METRIC_VAR_FSINODESTOTAL              = "fsinodestotal"
	METRIC_VAR_FSLIMITBYTES               = "fslimitbytes"
	METRIC_VAR_FSREADSBYTESTOTAL          = "fsreadsbytestotal"
	METRIC_VAR_FSWRITESBYTESTOTAL         = "fswritesbytestotal"
	METRIC_VAR_FSUSAGEBYTES               = "fsusagebytes"
	METRIC_VAR_PROCESSES                  = "processes"
	METRIC_VAR_NETWORKRECEIVEBYTESTOTAL   = "networkreceivebytestotal"
	METRIC_VAR_NETWORKRECEIVEERRORSTOTAL  = "networkreceiveerrorstotal"
	METRIC_VAR_NETWORKTRANSMITBYTESTOTAL  = "networktransmitbytestotal"
	METRIC_VAR_NETWORKTRANSMITERRORSTOTAL = "networktransmiterrorstotal"

	POD_STATUS_RUNNING   = "Running"
	POD_STATUS_PENDING   = "Pending"
	POD_STATUS_SUCCEEDED = "Succeeded"
	POD_STATUS_FAILED    = "Failed"
	POD_STATUS_UNKNOWN   = "Unknown"

	CONTAINER_STATUS_RUNNING    = "running"
	CONTAINER_STATUS_TERMINATED = "terminated"

	SUMMARY_DATATYPE_CURR = "current"
	SUMMARY_DATATYPE_PREV = "previous"
	SUMMARY_DATATYPE_CALC = "calculation"
	SUMMARY_DATATYPE_CNT  = "count"

	TB_ONTUNE_INFO                 = "ontuneinfo"
	TB_KUBE_TABLE_INFO             = "kubetableinfo"
	TB_KUBE_MANAGER_INFO           = "kubemanagerinfo"
	TB_KUBE_CLUSTER_INFO           = "kubeclusterinfo"
	TB_KUBE_RESOURCE_INFO          = "kuberesourceinfo"
	TB_KUBE_SC_INFO                = "kubescinfo"
	TB_KUBE_NS_INFO                = "kubensinfo"
	TB_KUBE_NODE_INFO              = "kubenodeinfo"
	TB_KUBE_NODESYSCO_INFO         = "kubenodesyscoinfo"
	TB_KUBE_POD_INFO               = "kubepodinfo"
	TB_KUBE_CONTAINER_INFO         = "kubecontainerinfo"
	TB_KUBE_ING_INFO               = "kubeinginfo"
	TB_KUBE_INGHOST_INFO           = "kubeinghostinfo"
	TB_KUBE_SVC_INFO               = "kubesvcinfo"
	TB_KUBE_DEPLOY_INFO            = "kubedeployinfo"
	TB_KUBE_STS_INFO               = "kubestsinfo"
	TB_KUBE_DS_INFO                = "kubedsinfo"
	TB_KUBE_RS_INFO                = "kubersinfo"
	TB_KUBE_PV_INFO                = "kubepvinfo"
	TB_KUBE_PVC_INFO               = "kubepvcinfo"
	TB_KUBE_EVENT_INFO             = "kubeeventinfo"
	TB_KUBE_LOG_INFO               = "kubeloginfo"
	TB_KUBE_SVC_INFO_V             = "kubesvcinfo_v"
	TB_KUBE_ING_INFO_V             = "kubeinginfo_v"
	TB_KUBE_SVCPOD_INFO_V          = "kubesvcpodinfo_v"
	TB_KUBE_INGPOD_INFO_V          = "kubeingpodinfo_v"
	TB_KUBE_LABELVALUE_INFO        = "kubelabelvalueinfo"
	TB_KUBE_LAST_NODE_PERF         = "kubelastrealtimeperfnode"
	TB_KUBE_LAST_POD_PERF          = "kubelastrealtimeperfpod"
	TB_KUBE_LAST_CONTAINER_PERF    = "kubelastrealtimeperfcontainer"
	TB_KUBE_LAST_NODE_NET_PERF     = "kubelastrealtimeperfnodenet"
	TB_KUBE_LAST_POD_NET_PERF      = "kubelastrealtimeperfpodnet"
	TB_KUBE_LAST_NODE_FS_PERF      = "kubelastrealtimeperfnodefs"
	TB_KUBE_LAST_POD_FS_PERF       = "kubelastrealtimeperfpodfs"
	TB_KUBE_LAST_CONTAINER_FS_PERF = "kubelastrealtimeperfcontainerfs"
	TB_KUBE_LAST_CLUSTER_PERF      = "kubelastrealtimeperfcluster"
	TB_KUBE_LAST_NAMESPACE_PERF    = "kubelastrealtimeperfns"
	TB_KUBE_LAST_REPLICASET_PERF   = "kubelastrealtimeperfrs"
	TB_KUBE_LAST_DAEMONSET_PERF    = "kubelastrealtimeperfds"
	TB_KUBE_LAST_STATEFULSET_PERF  = "kubelastrealtimeperfsts"
	TB_KUBE_LAST_DEPLOYMENT_PERF   = "kubelastrealtimeperfdeploy"
	TB_KUBE_LAST_SERVICE_PERF      = "kubelastrealtimeperfsvc"
	TB_KUBE_LAST_INGRESS_PERF      = "kubelastrealtimeperfing"
	TB_KUBE_NODE_PERF              = "kuberealtimeperfnode"
	TB_KUBE_POD_PERF               = "kuberealtimeperfpod"
	TB_KUBE_CONTAINER_PERF         = "kuberealtimeperfcontainer"
	TB_KUBE_NODE_NET_PERF          = "kuberealtimeperfnodenet"
	TB_KUBE_POD_NET_PERF           = "kuberealtimeperfpodnet"
	TB_KUBE_NODE_FS_PERF           = "kuberealtimeperfnodefs"
	TB_KUBE_POD_FS_PERF            = "kuberealtimeperfpodfs"
	TB_KUBE_CONTAINER_FS_PERF      = "kuberealtimeperfcontainerfs"
	TB_KUBE_CLUSTER_PERF           = "kuberealtimeperfcluster"
	TB_KUBE_NAMESPACE_PERF         = "kuberealtimeperfns"
	TB_KUBE_REPLICASET_PERF        = "kuberealtimeperfrs"
	TB_KUBE_DAEMONSET_PERF         = "kuberealtimeperfds"
	TB_KUBE_STATEFULSET_PERF       = "kuberealtimeperfsts"
	TB_KUBE_DEPLOYMENT_PERF        = "kuberealtimeperfdeploy"
	TB_KUBE_SERVICE_PERF           = "kuberealtimeperfsvc"
	TB_KUBE_INGRESS_PERF           = "kuberealtimeperfing"

	TB_KUBE_LAST_NODE_PERF_RAW         = "kubelastrealtimeperfnode_raw"
	TB_KUBE_LAST_POD_PERF_RAW          = "kubelastrealtimeperfpod_raw"
	TB_KUBE_LAST_CONTAINER_PERF_RAW    = "kubelastrealtimeperfcontainer_raw"
	TB_KUBE_LAST_NODE_NET_PERF_RAW     = "kubelastrealtimeperfnodenet_raw"
	TB_KUBE_LAST_POD_NET_PERF_RAW      = "kubelastrealtimeperfpodnet_raw"
	TB_KUBE_LAST_NODE_FS_PERF_RAW      = "kubelastrealtimeperfnodefs_raw"
	TB_KUBE_LAST_POD_FS_PERF_RAW       = "kubelastrealtimeperfpodfs_raw"
	TB_KUBE_LAST_CONTAINER_FS_PERF_RAW = "kubelastrealtimeperfcontainerfs_raw"
	TB_KUBE_NODE_PERF_RAW              = "kuberealtimeperfnode_raw"
	TB_KUBE_POD_PERF_RAW               = "kuberealtimeperfpod_raw"
	TB_KUBE_CONTAINER_PERF_RAW         = "kuberealtimeperfcontainer_raw"
	TB_KUBE_NODE_NET_PERF_RAW          = "kuberealtimeperfnodenet_raw"
	TB_KUBE_POD_NET_PERF_RAW           = "kuberealtimeperfpodnet_raw"
	TB_KUBE_NODE_FS_PERF_RAW           = "kuberealtimeperfnodefs_raw"
	TB_KUBE_POD_FS_PERF_RAW            = "kuberealtimeperfpodfs_raw"
	TB_KUBE_CONTAINER_FS_PERF_RAW      = "kuberealtimeperfcontainerfs_raw"

	TB_KUBE_FS_DEVICE_INFO     = "kubefsdeviceinfo"
	TB_KUBE_NET_INTERFACE_INFO = "kubenetinterfaceinfo"
	TB_KUBE_METRIC_ID_INFO     = "kubemetricidinfo"
)
